### ISSUE TITLE
Would really like "OFFSET" support

### ISSUE THREAD

**Issue by davidbuccola** [forcedotcom/java-sdk#13]
I was trying to work with a very large dataset by using paging techniques (query.setFirstResult() & query.setMaxResults()). I discovered that it didn't really work. A little more research and I found that there is a new SOQL option called "OFFSET" that DOES work for me through the REST interface.

It would be really nice if the JPA adapter could be updated to use the new SOQL "OFFSET" option to make query.setFirstResult() work correctly. Until that happens it looks like I am unable to use JPA for large datasets.

It is not a show stopper for me right now because I am temporarily switching over to the REST interface. I think this is something that will need to be addressed, however, before others try to use JPA for production applications.

**Comment by jesperfj** [comment]
This library is no longer maintained. I recommend using [wsc](https://github.com/forcedotcom/wsc) for connecting to Force.com API from Java apps.
