### ISSUE TITLE
Oddities in HTTPS vs. HTTP for force:// URLs

### ISSUE THREAD

**Issue by davidbuccola** [forcedotcom/java-sdk#14]
I was having some difficulties making the connections for JPA work in my test environment. I discovered that the JPA adapter is playing funny tricks when choosing between HTTP and HTTPS protocols. The JPA adapter uses HTTPS to talk to my public Dev org and uses HTTP to talk to my local development build. It was a surprise to me.

I looked at the JPA code and discovered that there is special code to do this. Unfortunately the special logic is messing me up. I am losing control to select the protocol I want. I want the same protocol for all my test environments but right now I get different protocols depending on my hostname.

I am working around the problem now but I think this special logic in JPA is a problem and is likely to mess customers up. If a customer accidentally has a DNS host name that includes the "internal" word then the customer will start getting the wrong kinds of connections. I suggest we remove the special logic from the JPA adapter and not base the HTTP protocol on the host name. It is risky.

**Comment by jesperfj** [comment]
This library is no longer maintained. I recommend using [wsc](https://github.com/forcedotcom/wsc) for connecting to Force.com API from Java apps.
