### ISSUE TITLE
Database.com sdk- Not able to pull more than 2000 records using query

### ISSUE THREAD

**Issue by vkanteti** [forcedotcom/java-sdk#21]
Hi ,

From my java application I'm not able to pull more than 2000 records using Query. I have seen querymore() can help in this, I'm using spring+jpa+force.sdk. Can somebody help me how to fetch all the data from my force objects.

Anyhelp is greatly appreciated.

Thanks.

**Comment by jesperfj** [comment]
This library is no longer maintained. I recommend using [wsc](https://github.com/forcedotcom/wsc) for connecting to Force.com API from Java apps.
