### ISSUE TITLE
Large number of objects causes long startup times

### ISSUE THREAD

**Issue by ustramooner** [forcedotcom/java-sdk#25]
On heroku, startup times can be significant for more than a few objects. The debug logs show:

Initialising Meta-Data for class XXX

Each call is taking ~500ms and sometimes as high as 3000ms. I believe that this is the bit where the java-sdk is fetching the metadata from force.com. This sometimes causes startup failures due to taking too long to startup on heroku.

If I'm not wrong, Force.com provides an API to allow querying more than one metadata object, so startup times could be significantly reduced by fetching the metadata for all metadata objects that will be required in a single call.

I haven't looked into how this could be achieved yet, but does anyone have any thoughts on this?

**Comment by jesperfj** [comment]
This library is no longer maintained. I recommend using [wsc](https://github.com/forcedotcom/wsc) for connecting to Force.com API from Java apps.
