### ISSUE TITLE
oauth cookies

### ISSUE THREAD

**Issue by ustramooner** [forcedotcom/java-sdk#26]
Seems that oauth is depositing cookies on almost every call (I end up with a cookie at every directory level of the website). This should be reduced, but the problem is that the (other) cookies cause the session to be invalidated due to the session id in the session (when using session) not matching the force_sid cookie. This can happen after a logout or an expired session.

I think it's best to set the cookie path to make sure only 1 cookie is set and to avoid having different sid's.

Please have a look at these suggested changes:

https://github.com/ustramooner/java-sdk/commit/9c0185ce8f9358fa8376ef7e7724c75c4777f83a
https://github.com/ustramooner/java-sdk/commit/444b52acfc3c506da1e79a8273a7e63243ad81d4

**Comment by jesperfj** [comment]
This library is no longer maintained. I recommend using [wsc](https://github.com/forcedotcom/wsc) for connecting to Force.com API from Java apps.
