### ISSUE TITLE
Upgrade to use DN3.1+

### ISSUE THREAD

**Issue by datanucleus** [forcedotcom/java-sdk#27]
DataNucleus v2.x hasn't been maintained for some time now (more than a year). DataNucleus 3.0 is also no longer maintained. Strongly suggest that you upgrade your plugin to use something recent (DN3.1, or DN3.2 milestone releases)

**Comment by jesperfj** [comment]
This library is no longer maintained. I recommend using [wsc](https://github.com/forcedotcom/wsc) for connecting to Force.com API from Java apps.
