### ISSUE TITLE
LogoutSuccessHandler does not clear SDK related cookies

### ISSUE THREAD

**Issue by oscartcy-hmn** [forcedotcom/java-sdk#30]
I use SecurityContextCookieStore as security context storage service. Then I set the cookie path as "/" to make the cookies available to the whole site. However after I call the logout endpoint (with SDK LogoutSuccessHandler), those cookies does not clear. User can access the protected resources again without login.

When user logout, LogoutSuccessHandler calls SecurityContextService to clear all related cookies. From source code, clear cookie process does not specifiy the cookie path. From http spec (http://www.w3.org/Protocols/rfc2109/rfc2109), "Path   Defaults to the path of the request URL that generated the Set-Cookie response, up to, but not including, the right-most /." If the SDK does not specific the path when clearing cookies, it just clear the cookies under the logout path. In my site login and logout endpoint are at two separate path, so I think this is the root course of the unexpected behaviour. Any suggestions?

**Comment by jesperfj** [comment]
This library is no longer maintained. I recommend using [wsc](https://github.com/forcedotcom/wsc) for connecting to Force.com API from Java apps.
