### ISSUE TITLE
Java Spring Security stop working missing Salesforce XML schema

### ISSUE THREAD

**Issue by iandrosov** [forcedotcom/java-sdk#31]
Salesforce Spring Security Schema URL suddenly returns 404 and Java apps built with OAUth on DB.com SDK stop working on Heroku. Any idea where this URL has moved: http://www.salesforce.com/schema/springsecurity?
Error result form Spring web app:
org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 18 in XML document from ServletContext resource [/WEB-INF/spring/security-config.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 18; columnNumber: 49; cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'fss:oauth'.

There is a definition: xmlns:fss="http://www.salesforce.com/schema/springsecurity"

Additional note: Another URL schema: http://media.developerforce.com/schema/force-springsecurity-1.2.xsd also returns Access denied instead of schema file.

**Comment by todc** [comment]
I ran into the same issue a couple weeks ago. The issue, I believe, is with the media.developerforce.com URL, not the salesforce.com URL. Given the age of the repo and the lack of recent activity, I'm guessing the XSD files won't be made available again.

I was able to find archived versions of the XSD file at:

http://grepcode.com/file/repo1.maven.org/maven2/com.force.sdk/force-springsecurity/22.0.8-BETA/com/force/sdk/springsecurity/config/force-springsecurity-1.2.xsd?av=f

You can package that file into your app and refer to the local copy instead, e.g.:

    <beans xmlns="http://www.springframework.org/schema/beans"
           xsi:schemaLocation="http://www.salesforce.com/schema/springsecurity
                               classpath:force-springsecurity-1.2.xsd">
    ...
    </beans>

There's probably a better way, but that's what I was able to get working. Good luck!

**Comment by iandrosov** [comment]
Thank you @todc for this valuable insight! This has resolved my problem. I now host this "deprecated" fiorsce-springsecurity-1.2.xsd on Heroku to give access to may apps. Sharing my public URL here so it may help others. http://force-spring.herokuapp.com/force-springsecurity-1.2.xsd

**Comment by ferozmuslim** [comment]
Thank you @todc for the solution. And thank you @iandrosov for hosting the .xsd on your site. I faced the same issue and it's resolved now.

**Comment by jesperfj** [comment]
This library is no longer maintained. I recommend using [wsc](https://github.com/forcedotcom/wsc) for connecting to Force.com API from Java apps.
