### ISSUE TITLE
CustomSecurityContext.setEndPointHost sets the wrong property

### ISSUE THREAD

**Issue by walker1c** [forcedotcom/java-sdk#32]
Presumably this method should invoke setEndPointHost(), not setEndPoint() on the embedded ForceSecurityContext.
```java
    @Override
    public final void setEndPointHost(String endPointHost) {
        forceSecurityContext.setEndPoint(endPointHost);
    }
```

**Comment by jesperfj** [comment]
This library is no longer maintained. Please use [wsc](https://github.com/forcedotcom/wsc) for connecting to Force.com API from Java apps.
