### ISSUE TITLE
PostLoad not always called

### ISSUE THREAD

**Issue by davidbuccola** [forcedotcom/java-sdk#6]
I am working with a slightly more advanced object that requires a @PostLoad method. I found that the JPA adapter is not reliably calling the method annotated with @PostLoad. The method gets called if the object is explicitly loaded but not if the object is implicitly loaded. 

This works:

    author = entityManager.find(Author.class, authorId);  // The @PostLoad method gets called for author

This does NOT work:

    book = entityManager.find(Book.class, bookId);
    author = book.getAuthor(); // The @PostLoad is NOT called for author

P.S. - Yes, the Book and Author class have a relationship defined between them.

**Comment by jesperfj** [comment]
This library is no longer maintained. I recommend using [wsc](https://github.com/forcedotcom/wsc) for connecting to Force.com API from Java apps.
