### ISSUE TITLE
DataNucleus JDOFatalUserException: No metadata has been registered for class

### ISSUE THREAD

**Issue by keithpeters** [forcedotcom/java-sdk#9]
I generated entities for my force.com application using the maven-force-plugin.

Then I created a simple main program to connect to my org and load a Contact entity:

``` java
    public static void main(String[] args) {
        EntityManager em = 
            Persistence
                .createEntityManagerFactory(PERSISTENCE_UNIT_NAME)
                .createEntityManager();
        try {
            System.out.println("Contact: " + em.find(Contact.class, CONTACT_ID));
        }
        finally {
            em.close();
        }
    }
```

When I run this I get the following exception:

<pre>
    Exception in thread "main" javax.jdo.JDOFatalUserException: No metadata has been registered for class com.claimvantagecorp.model.Contact.
        at javax.jdo.spi.JDOImplHelper.getMeta(JDOImplHelper.java:493)
        at javax.jdo.spi.JDOImplHelper.newInstance(JDOImplHelper.java:227)
        at org.datanucleus.jdo.state.JDOStateManagerImpl.initialiseForHollow(JDOStateManagerImpl.java:253)
        at org.datanucleus.state.StateManagerFactory.newStateManagerForHollow(StateManagerFactory.java:56)
        at org.datanucleus.ObjectManagerImpl.findObject(ObjectManagerImpl.java:2772)
        at org.datanucleus.jpa.EntityManagerImpl.find(EntityManagerImpl.java:305)
        at com.force.sdk.jpa.ForceEntityManager.find(ForceEntityManager.java:294)
        at org.datanucleus.jpa.EntityManagerImpl.find(EntityManagerImpl.java:236)
</pre>

When I breakpoint the line that registers a classes jdo metadata, JDOImplHelper.java:364, I can see that the mapped superclasses of the entities are being added but not the entities them selves.

Btw, this is the debug output:

<pre>
    17:02:58 INFO  [Persistence] - Property datanucleus.rdbms.stringDefaultLength unknown - will be ignored
    17:02:58 INFO  [Persistence] - ================= Persistence Configuration ===============
    17:02:58 INFO  [Persistence] - DataNucleus Persistence Factory - Vendor: "DataNucleus"  Version: "2.2.3"
    17:02:58 INFO  [Persistence] - DataNucleus Persistence Factory initialised for datastore URL="" driver="" userName=""
    17:02:58 INFO  [Persistence] - ===========================================================
    17:02:58 INFO  [Persistence] - Property force.ConnectionName unknown - will be ignored
    17:02:58 INFO  [MetaData] - Not found any metadata mapping files for resource name META-INF/orm.xml in CLASSPATH
    17:02:59 INFO  [MetaData] - Class "com.example.model.Account" has been specified with JPA annotations so using those.
    17:02:59 INFO  [MetaData] - Class "com.example.model.Contact" has been specified with JPA annotations so using those.
    17:02:59 INFO  [MetaData] - Class "com.example.model.UserRole" has been specified with JPA annotations so using those.
    17:02:59 INFO  [MetaData] - Class "com.example.model.BusinessProcess" has been specified with JPA annotations so using those.
    17:02:59 INFO  [MetaData] - Class "com.example.model.Organization" has been specified with JPA annotations so using those.
    17:02:59 INFO  [MetaData] - Class "com.example.model.RecordType" has been specified with JPA annotations so using those.
    17:02:59 INFO  [MetaData] - Class "com.force.sdk.jpa.model.ForceOwner" has been specified with JPA annotations so using those.
    17:02:59 INFO  [MetaData] - Class "com.example.model.CallCenter" has been specified with JPA annotations so using those.
    17:02:59 INFO  [MetaData] - Class "com.example.model.Profile" has been specified with JPA annotations so using those.
    17:02:59 INFO  [MetaData] - Class "com.example.model.Dates" has been specified with JPA annotations so using those.
    17:02:59 INFO  [MetaData] - Class "com.example.model.Group" has been specified with JPA annotations so using those.
    17:02:59 INFO  [MetaData] - Class "com.example.model.UserLicense" has been specified with JPA annotations so using those.
    17:02:59 INFO  [MetaData] - Class "com.example.model.User" has been specified with JPA annotations so using those.
    17:02:59 INFO  [MetaData] - Class "com.force.sdk.jpa.model.BaseForceStandardObject" has been specified with JPA annotations so using those.
    17:02:59 INFO  [MetaData] - Class "com.force.sdk.jpa.model.BaseForceObject" has been specified with JPA annotations so using those.
    17:02:59 INFO  [MetaData] - Class "com.force.sdk.jpa.model.BaseForceCustomObject" has been specified with JPA annotations so using those.
    17:02:59 INFO  [connector] - Connection : Creating AbsenceJpaTest from environment variable: FORCE_JPATEST_URL
    17:03:13 INFO  [Persistence] - Managing Persistence of Class : com.force.sdk.jpa.model.BaseForceObject [Table : (none), InheritanceStrategy : subclass-table]
    17:03:13 INFO  [Persistence] - Managing Persistence of Class : com.example.model.CallCenter [Table : (none), InheritanceStrategy : new-table]
    17:03:13 INFO  [Persistence] - Managing Persistence of Class : com.example.model.UserLicense [Table : (none), InheritanceStrategy : new-table]
    17:03:13 INFO  [Persistence] - Managing Persistence of Class : com.example.model.Profile [Table : (none), InheritanceStrategy : new-table]
    17:03:13 INFO  [Persistence] - Managing Persistence of Class : com.example.model.UserRole [Table : (none), InheritanceStrategy : new-table]
    17:03:13 INFO  [Persistence] - Managing Persistence of Class : com.example.model.User [Table : (none), InheritanceStrategy : new-table]
    17:03:13 INFO  [Persistence] - Managing Persistence of Class : com.force.sdk.jpa.model.ForceOwner [Table : (none), InheritanceStrategy : new-table]
    17:03:13 INFO  [Persistence] - Managing Persistence of Class : com.force.sdk.jpa.model.BaseForceStandardObject [Table : (none), InheritanceStrategy : subclass-table]
    17:03:13 INFO  [Persistence] - Managing Persistence of Class : com.example.model.Account [Table : (none), InheritanceStrategy : new-table]
    17:03:13 INFO  [Persistence] - Managing Persistence of Class : com.example.model.BusinessProcess [Table : (none), InheritanceStrategy : new-table]
    17:03:13 INFO  [Persistence] - Managing Persistence of Class : com.example.model.RecordType [Table : (none), InheritanceStrategy : new-table]
    17:03:13 INFO  [Persistence] - Managing Persistence of Class : com.force.sdk.jpa.model.BaseForceCustomObject [Table : (none), InheritanceStrategy : subclass-table]
    17:03:13 INFO  [Persistence] - Managing Persistence of Class : com.example.model.Contact [Table : (none), InheritanceStrategy : new-table]
    Exception in thread "main" javax.jdo.JDOFatalUserException: No metadata has been registered for class com.example.model.Contact.
</pre>

Btw, I tried posting this as a question on stackoverflow but the tag _database.com_ hasn't been created yet and (I'm ashamed to say :(), I don't have the reputation to create one. Any help or pointers would be much appreciated.

**Comment by CSAC1** [comment]
Hi Does anyone have a fix for this? I have generated classes using force 22.0.7 version and enhanced it with 2.1.0 release. I also face classCastExceptions!
